name: ci

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install
      - run: sbt test

